[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.ctype",
  "php82Extensions.fileinfo",
  "php82Extensions.curl",
  "php82Extensions.openssl",
  "php82Extensions.bcmath",
  "composer"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
  "php -m", 
  "php artisan config:clear",
  "php artisan config:cache"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"